
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hokxgprnefnztcnixlxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhva3hncHJuZWZuenRjbml4bHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mzc2MjcsImV4cCI6MjA2NjUxMzYyN30.xGx9w3TCdLjOmYGQYtINhq69uWFgWFcvFtsQCFr5VG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
